version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - DIYgod
  labels:
  - dependencies
  ignore:
  - dependency-name: webpack
    versions:
    - 5.26.2
    - 5.27.2
    - 5.28.0
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.35.0
    - 5.35.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.5.0
    - 4.5.0
    - 4.6.0
    - 4.6.0
    - 4.6.0
    - 4.6.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.1.0
  - dependency-name: postcss-loader
    versions:
    - 5.1.0
